--UNIVERSITY DB SQLSERVER

--1. Realizar una consulta donde pueda obtener los paises donde estan ubicadas cada universidad.
SELECT U.UNIVERSITY_NAME ,C.COUNTRY_NAME  FROM UNIVERSITY U 
INNER JOIN COUNTRY C ON U.COUNTRY_ID = C.ID ;

--2. Conocer cuantas universidades hay en cada pais.
SELECT C.COUNTRY_NAME , COUNT(U.ID) 'CANTIDAD DE UNIVERSIDADES' FROM COUNTRY C 
INNER JOIN UNIVERSITY U ON C.ID =U.COUNTRY_ID 
GROUP BY C.COUNTRY_NAME 
ORDER BY C.COUNTRY_NAME ASC

--3. Conocer cuantos paises no tienen universidades en el ranking.
SELECT COUNT(DISTINCT U.COUNTRY_ID) AS CANTIDAD_PAISES_SIN_UNIVERSIDADES
FROM UNIVERSITIES.DBO.UNIVERSITY AS U
LEFT JOIN UNIVERSITIES.DBO.UNIVERSITY_RANKING_YEAR AS URY ON U.ID = URY.UNIVERSITY_ID
WHERE URY.UNIVERSITY_ID IS NULL;

--4. Mostrar los criterios de cada tipo de ranking.
SELECT RS.SYSTEM_NAME, RC.CRITERIA_NAME
FROM UNIVERSITIES.DBO.RANKING_SYSTEM AS RS
JOIN UNIVERSITIES.DBO.RANKING_CRITERIA AS RC ON RS.ID = RC.RANKING_SYSTEM_ID;

--5. Conocer el ranking que tiene mas criterios
SELECT RS.SYSTEM_NAME, COUNT(RC.ID) AS NUM_CRITERIA
FROM UNIVERSITIES.DBO.RANKING_SYSTEM AS RS
JOIN UNIVERSITIES.DBO.RANKING_CRITERIA AS RC ON RS.ID = RC.RANKING_SYSTEM_ID
GROUP BY RS.ID, RS.SYSTEM_NAME
ORDER BY NUM_CRITERIA DESC;

--6. Cual es el top de universidades de forma descendente del ano 2012 por cada criterio
SELECT RC.CRITERIA_NAME, U.UNIVERSITY_NAME, URY.SCORE
FROM UNIVERSITIES.DBO.UNIVERSITY_RANKING_YEAR AS URY
JOIN UNIVERSITIES.DBO.RANKING_CRITERIA AS RC ON URY.RANKING_CRITERIA_ID = RC.ID
JOIN UNIVERSITIES.DBO.UNIVERSITY AS U ON URY.UNIVERSITY_ID = U.ID
WHERE URY.YEAR = 2012
ORDER BY RC.CRITERIA_NAME, URY.SCORE DESC;

--7. Mostrar las 5 universidad con mas cantidades de score 100 del ranking tipo 'Center for World University Rankings'
SELECT TOP 5 U.UNIVERSITY_NAME, URY.SCORE
FROM UNIVERSITIES.DBO.UNIVERSITY_RANKING_YEAR AS URY
JOIN UNIVERSITIES.DBO.UNIVERSITY AS U ON URY.UNIVERSITY_ID = U.ID
JOIN UNIVERSITIES.DBO.RANKING_CRITERIA AS RC ON URY.RANKING_CRITERIA_ID = RC.ID
JOIN UNIVERSITIES.DBO.RANKING_SYSTEM AS RS ON RC.RANKING_SYSTEM_ID = RS.ID
WHERE RS.SYSTEM_NAME = 'CENTER FOR WORLD UNIVERSITY RANKINGS' AND URY.SCORE = 100
ORDER BY URY.SCORE DESC;

--8. Mostrar que paises se posicionaron con universidades con un score mayor a 90
SELECT C.COUNTRY_NAME
FROM UNIVERSITIES.DBO.UNIVERSITY_RANKING_YEAR AS URY
JOIN UNIVERSITIES.DBO.UNIVERSITY AS U ON URY.UNIVERSITY_ID = U.ID
JOIN UNIVERSITIES.DBO.COUNTRY AS C ON U.COUNTRY_ID = C.ID
WHERE URY.SCORE > 90
GROUP BY C.COUNTRY_NAME;

--9. Mostrar las universidades que utilizan los criterios del tipo ranking 'Shangai Ranking'
SELECT U.UNIVERSITY_NAME
FROM UNIVERSITIES.DBO.UNIVERSITY_RANKING_YEAR AS URY
JOIN UNIVERSITIES.DBO.RANKING_CRITERIA AS RC ON URY.RANKING_CRITERIA_ID = RC.ID
JOIN UNIVERSITIES.DBO.RANKING_SYSTEM AS RS ON RC.RANKING_SYSTEM_ID = RS.ID
JOIN UNIVERSITIES.DBO.UNIVERSITY AS U ON URY.UNIVERSITY_ID = U.ID
WHERE RS.SYSTEM_NAME = 'SHANGHAI RANKING'
GROUP BY U.UNIVERSITY_NAME;

--10.Mostrar el top 10 de las peores posiciones del tipo ranking 'Times Higher....'
SELECT TOP 10 U.UNIVERSITY_NAME, URY.SCORE
FROM UNIVERSITIES.DBO.UNIVERSITY_RANKING_YEAR AS URY
JOIN UNIVERSITIES.DBO.RANKING_CRITERIA AS RC ON URY.RANKING_CRITERIA_ID = RC.ID
JOIN UNIVERSITIES.DBO.RANKING_SYSTEM AS RS ON RC.RANKING_SYSTEM_ID = RS.ID
JOIN UNIVERSITIES.DBO.UNIVERSITY AS U ON URY.UNIVERSITY_ID = U.ID
WHERE RS.SYSTEM_NAME = 'TIMES HIGHER EDUCATION WORLD UNIVERSITY RANKING'
      AND URY.YEAR = 2012
ORDER BY URY.SCORE ASC;
