------------------------- SUPERHEROES DB----------------------------

--1. Mostrar una lista de los superpoderes que tiene cada Super Heroe
SELECT S.SUPERHERO_NAME, P.POWER_NAME
FROM SUPERHERO.DBO.SUPERHERO AS S
JOIN SUPERHERO.DBO.HERO_POWER AS HP ON S.ID = HP.HERO_ID
JOIN SUPERHERO.DBO.SUPERPOWER AS P ON HP.POWER_ID = P.ID;

--2. Mostrar la cantidad de superpoderes con los que cuenta cada Super Heroe
SELECT S.SUPERHERO_NAME, COUNT(HP.POWER_ID) AS TOTAL_SUPERPOWERS
FROM SUPERHERO.DBO.SUPERHERO AS S
LEFT JOIN SUPERHERO.DBO.HERO_POWER AS HP ON S.ID = HP.HERO_ID
GROUP BY S.SUPERHERO_NAME;

--3. Mostrar los diez superpoderes que es mas frecuente en cada Super Heroe
SELECT S.SUPERHERO_NAME, SP.POWER_NAME, COUNT(HP.POWER_ID) AS POWER_COUNT
FROM SUPERHERO.DBO.SUPERHERO AS S
JOIN SUPERHERO.DBO.HERO_POWER AS HP ON S.ID = HP.HERO_ID
JOIN SUPERHERO.DBO.SUPERPOWER AS SP ON HP.POWER_ID = SP.ID
GROUP BY S.SUPERHERO_NAME, SP.POWER_NAME
ORDER BY S.SUPERHERO_NAME, POWER_COUNT DESC;

--4. Mostrar los diez superpoderes que es mas frecuente en cada Super Heroe
SELECT S.SUPERHERO_NAME, SP.POWER_NAME, COUNT(HP.POWER_ID) AS POWER_COUNT
FROM SUPERHERO.DBO.SUPERHERO AS S
JOIN SUPERHERO.DBO.HERO_POWER AS HP ON S.ID = HP.HERO_ID
JOIN SUPERHERO.DBO.SUPERPOWER AS SP ON HP.POWER_ID = SP.ID
GROUP BY S.SUPERHERO_NAME, SP.POWER_NAME
HAVING COUNT(HP.POWER_ID) > 0
ORDER BY S.SUPERHERO_NAME, POWER_COUNT DESC
OFFSET 0 ROWS
FETCH NEXT 10 ROWS ONLY;

--5. Mostrar los Super Heroes que no cuentan con el Atributo de Intelligence
SELECT SH.SUPERHERO_NAME
FROM SUPERHERO.DBO.SUPERHERO AS SH
LEFT JOIN SUPERHERO.DBO.HERO_ATTRIBUTE AS HA ON SH.ID = HA.HERO_ID
LEFT JOIN SUPERHERO.DBO.ATTRIBUTE AS A ON HA.ATTRIBUTE_ID = A.ID
WHERE A.ATTRIBUTE_NAME IS NULL OR A.ATTRIBUTE_NAME <> 'INTELLIGENCE';

--6. Mostrar los Super Heroes que cuentan con tres o 5 Atributos
SELECT SH.SUPERHERO_NAME
FROM SUPERHERO.DBO.SUPERHERO AS SH
JOIN SUPERHERO.DBO.HERO_ATTRIBUTE AS HA ON SH.ID = HA.HERO_ID
JOIN SUPERHERO.DBO.ATTRIBUTE AS A ON HA.ATTRIBUTE_ID = A.ID
GROUP BY SH.ID, SH.SUPERHERO_NAME
HAVING COUNT(DISTINCT HA.ATTRIBUTE_ID) IN (3, 5);

--7. Mostrar la lista de las mujeres que son Super Heroes
SELECT SH.SUPERHERO_NAME, SH.FULL_NAME
FROM SUPERHERO.DBO.SUPERHERO AS SH
JOIN SUPERHERO.DBO.GENDER AS G ON SH.GENDER_ID = G.ID
WHERE G.GENDER = 'FEMALE';

--8. Mostrar la lista de los colores de como se identifca un Super Heroe (color de ojos, traje y pelo)
SELECT S.SUPERHERO_NAME, E.COLOUR AS EYE_COLOUR, H.COLOUR AS HAIR_COLOUR, SK.COLOUR AS SKIN_COLOUR
FROM SUPERHERO.DBO.SUPERHERO AS S
JOIN SUPERHERO.DBO.COLOUR AS E ON S.EYE_COLOUR_ID = E.ID
JOIN SUPERHERO.DBO.COLOUR AS H ON S.HAIR_COLOUR_ID = H.ID
JOIN SUPERHERO.DBO.COLOUR AS SK ON S.SKIN_COLOUR_ID = SK.ID;

--9. Mostrar la lista de Super Heroe indicando su origen (race) y cantidad de superpoderes
SELECT S.SUPERHERO_NAME, R.RACE, COUNT(SP.ID) AS CANTIDAD_SUPERPODERES
FROM SUPERHERO.DBO.SUPERHERO AS S
JOIN SUPERHERO.DBO.RACE AS R ON S.RACE_ID = R.ID
LEFT JOIN SUPERHERO.DBO.SUPERPOWER AS SP ON S.ID = SP.ID
GROUP BY S.SUPERHERO_NAME, R.RACE;

--10. Mostrar la cantidad de superheroes que tienen un papel de Superheroe Bueno(alignment) agrupado por cada editor(publisher)
SELECT P.PUBLISHER_NAME, COUNT(S.ID) AS CANTIDAD_SUPERHEROES
FROM SUPERHERO.DBO.SUPERHERO AS S
JOIN SUPERHERO.DBO.ALIGNMENT AS A ON S.ALIGNMENT_ID = A.ID
JOIN SUPERHERO.DBO.PUBLISHER AS P ON S.PUBLISHER_ID = P.ID
WHERE A.ALIGNMENT = 'BUENO'
GROUP BY P.PUBLISHER_NAME;
