--1.Mostrar una lista de los libros con el autor e idiomas del libro
SELECT B.TITLE,A.AUTHOR_NAME,BL.LANGUAGE_NAME
FROM BOOK B
INNER JOIN BOOK_AUTHOR BA
ON B.BOOK_ID = BA.BOOK_ID
INNER JOIN BOOK_LANGUAGE BL
ON B.LANGUAGE_ID = BL.LANGUAGE_ID
INNER JOIN AUTHOR A
ON BA.AUTHOR_ID = A.AUTHOR_ID

--2.Obtener la cantidad de compras que ha realizado un cliente
SELECT C.FIRST_NAME,C.LAST_NAME,COUNT(CO.ORDER_DATE) AS CANTIDAD_COMPRAS
FROM CUSTOMER C
INNER JOIN CUST_ORDER CO
ON C.CUSTOMER_ID = CO.CUSTOMER_ID
GROUP BY C.FIRST_NAME,C.LAST_NAME

--3.Listar los 5 libros mas vendidos
SELECT TOP 5 B.TITLE,COUNT(HO.ORDER_ID) AS VENDIDOS
FROM ORDER_LINE OL
INNER JOIN ORDER_HISTORY HO
ON OL.ORDER_ID = HO.ORDER_ID
INNER JOIN BOOK B
ON OL.BOOK_ID = B.BOOK_ID
where HO.STATUS_ID ='1'
GROUP BY B.TITLE,HO.STATUS_ID
ORDER BY 2 DESC

--4.Mostrar los paises donde se ha utilizado el tipo de envio Express
SELECT C.COUNTRY_NAME,CUS.METHOD_NAME
FROM SHIPPING_METHOD SM
INNER JOIN CUST_ORDER CUS
ON SM.METHOD_ID = CUS.SHIPPING_METHOD_ID
INNER JOIN ADDRESS AD
CUS.DEST_ADDRESS_ID = AD.ADDRESS_ID
INNER JOIN COUNTRY C
AD.COUNTRY_ID = C.COUNTRY_ID

--5.Mostrar los libros que sus ordenes se han cancelado
SELECT B.TITLE,OS.STATUS_VALUE,HO.ORDER_ID
FROM ORDER_LINE OL
INNER JOIN ORDER_HISTORY HO
ON OL.ORDER_ID = HO.ORDER_ID
INNER JOIN BOOK B
ON OL.BOOK_ID = B.BOOK_ID
INNER JOIN ORDER_STATUS OS
ON HO.STATUS_ID = OS.STATUS_ID
where HO.STATUS_ID ='5'

--6.Mostrar el pais donde tiene mas influencia cada autor de libro
select *from book_author;
select *from author;
select *from country;-------
select *from book;
select *from book_language;
select *from CUST_ORDER;--------
select *from CUSTOMER;
select *from ORDER_LINE;
select *from PUBLISHER;
select *from SHIPPING_METHOD;-----
select *from ADDRESS_STATUS;
select *from ADDRESS;--------
select *from ORDER_HISTORY;
select *from CUSTOMER_ADDRESS;
select *from ORDER_STATUS;

--7.Mostrar los clientes que han retornado o devuelto libros
SELECT C.FIRST_NAME,C.LAST_NAME,B.TITLE,OS.STATUS_VALUE
FROM ORDER_LINE OL
INNER JOIN ORDER_HISTORY HO
ON OL.ORDER_ID = HO.ORDER_ID
INNER JOIN BOOK B
ON OL.BOOK_ID = B.BOOK_ID
INNER JOIN ORDER_STATUS OS
ON HO.STATUS_ID = OS.STATUS_ID
INNER JOIN CUST_ORDER CO
ON HO.ORDER_ID = CO.ORDER_ID
INNER JOIN CUSTOMER C
ON CO.CUSTOMER_ID = C.CUSTOMER_ID
where HO.STATUS_ID ='6'

--8.Mostrar la cantidad de libros y el titulo del libro que se han entregado satisfactoriamente
SELECT B.TITLE,OS.STATUS_VALUE,COUNT(OL.ORDER_ID) AS CANTIDAD_ENTREGADA
FROM ORDER_LINE OL
INNER JOIN ORDER_HISTORY HO
ON OL.ORDER_ID = HO.ORDER_ID
INNER JOIN BOOK B
ON OL.BOOK_ID = B.BOOK_ID
INNER JOIN ORDER_STATUS OS
ON HO.STATUS_ID = OS.STATUS_ID
where HO.STATUS_ID ='1'
GROUP BY B.TITLE,OS.STATUS_VALUE
ORDER BY 3 DESC

--9.Mostrar la lista de los clientes mas frecuentes
SELECT C.FIRST_NAME,C.LAST_NAME,OS.STATUS_VALUE,COUNT(OL.ORDER_ID) AS CANTIDAD_ENTREGADA
FROM ORDER_LINE OL
INNER JOIN ORDER_HISTORY HO
ON OL.ORDER_ID = HO.ORDER_ID
INNER JOIN BOOK B
ON OL.BOOK_ID = B.BOOK_ID
INNER JOIN ORDER_STATUS OS
ON HO.STATUS_ID = OS.STATUS_ID
INNER JOIN CUST_ORDER CO
ON HO.ORDER_ID = CO.ORDER_ID
INNER JOIN CUSTOMER C
ON CO.CUSTOMER_ID = C.CUSTOMER_ID
where HO.STATUS_ID ='1'
GROUP BY C.FIRST_NAME,C.LAST_NAME,OS.STATUS_VALUE
ORDER BY CANTIDAD_ENTREGADA DESC

--10.Mostrar el mes en el que mas pedidos de libros se realizan
SELECT B.TITLE,COUNT(HO.ORDER_ID) AS VENDIDOS,HO.STATUS_DATE
FROM ORDER_LINE OL
INNER JOIN ORDER_HISTORY HO
ON OL.ORDER_ID = HO.ORDER_ID
INNER JOIN BOOK B
ON OL.BOOK_ID = B.BOOK_ID
where HO.STATUS_ID ='1'
GROUP BY B.TITLE,HO.STATUS_ID,HO.STATUS_DATE
ORDER BY 2 DESC