
-------------------VIDEOGAME DB---------------------------
--1.Mostrar la lista de juegos con el genero
SELECT G.GAME_NAME, GE.GENRE_NAME
FROM VIDEO_GAMES.DBO.GAME AS G
JOIN VIDEO_GAMES.DBO.GAME_PUBLISHER AS GP ON G.ID = GP.GAME_ID
JOIN VIDEO_GAMES.DBO.GENRE AS GE ON G.GENRE_ID = GE.ID;

--2.Mostrar la lista de juegos que tiene cada Plataforma
SELECT P.PLATFORM_NAME, G.GAME_NAME
FROM VIDEO_GAMES.DBO.PLATFORM AS P
JOIN VIDEO_GAMES.DBO.GAME_PLATFORM AS GP ON P.ID = GP.PLATFORM_ID
JOIN VIDEO_GAMES.DBO.GAME_PUBLISHER AS GPUB ON GP.GAME_PUBLISHER_ID = GPUB.ID
JOIN VIDEO_GAMES.DBO.GAME AS G ON GPUB.GAME_ID = G.ID;

--3.Mostrar los juegos lanzados antes del año 2000
SELECT G.GAME_NAME
FROM VIDEO_GAMES.DBO.GAME_PLATFORM AS GP
JOIN VIDEO_GAMES.DBO.GAME AS G ON GP.ID = G.ID
WHERE GP.RELEASE_YEAR < 2000;

--4.Mostrar los juegos mas vendidos en Europa
SELECT G.GAME_NAME, RS.NUM_SALES
FROM VIDEO_GAMES.DBO.GAME_PLATFORM AS GP
JOIN VIDEO_GAMES.DBO.REGION_SALES AS RS ON GP.ID = RS.GAME_PLATFORM_ID
JOIN VIDEO_GAMES.DBO.GAME AS G ON GP.ID = G.ID
JOIN VIDEO_GAMES.DBO.REGION AS R ON RS.REGION_ID = R.ID
WHERE R.REGION_NAME = 'EUROPA'
ORDER BY RS.NUM_SALES DESC;

--5.Mostrar los juegos con ventas menores al 0.5 de la plataforma Wii durante la decada del 2000
SELECT G.GAME_NAME, RS.NUM_SALES
FROM VIDEO_GAMES.DBO.GAME_PLATFORM AS GP
JOIN VIDEO_GAMES.DBO.REGION_SALES AS RS ON GP.ID = RS.GAME_PLATFORM_ID
JOIN VIDEO_GAMES.DBO.GAME AS G ON GP.ID = G.ID
WHERE GP.PLATFORM_ID = (SELECT ID FROM VIDEO_GAMES.DBO.PLATFORM WHERE PLATFORM_NAME = 'WII')
  AND GP.RELEASE_YEAR BETWEEN 2000 AND 2009
  AND RS.NUM_SALES < 0.5;

--6.Mostrar la lista de juegos de PlayStation
SELECT G.GAME_NAME
FROM VIDEO_GAMES.DBO.GAME AS G
JOIN VIDEO_GAMES.DBO.GAME_PLATFORM AS GP ON G.ID = GP.GAME_PUBLISHER_ID
JOIN VIDEO_GAMES.DBO.PLATFORM AS P ON GP.PLATFORM_ID = P.ID
WHERE P.PLATFORM_NAME = 'PLAYSTATION';

--7.Cuales son los 5 generos de juego que mas se venden en Europa
SELECT GENRE.GENRE_NAME, SUM(RS.NUM_SALES) AS TOTAL_SALES
FROM VIDEO_GAMES.DBO.GAME AS GAME
JOIN VIDEO_GAMES.DBO.GENRE AS GENRE ON GAME.GENRE_ID = GENRE.ID
JOIN VIDEO_GAMES.DBO.GAME_PUBLISHER AS GP ON GAME.ID = GP.GAME_ID
JOIN VIDEO_GAMES.DBO.GAME_PLATFORM AS GPL ON GP.ID = GPL.GAME_PUBLISHER_ID
JOIN VIDEO_GAMES.DBO.REGION_SALES AS RS ON GPL.ID = RS.GAME_PLATFORM_ID
JOIN VIDEO_GAMES.DBO.REGION AS REGION ON RS.REGION_ID = REGION.ID
WHERE REGION.REGION_NAME = 'EUROPE'
GROUP BY GENRE.GENRE_NAME
ORDER BY TOTAL_SALES DESC;

--8.Que editores tienen mejor presencia en el mercado de ventas de Norte America
SELECT PUBLISHER.PUBLISHER_NAME, SUM(RS.NUM_SALES) AS TOTAL_SALES
FROM VIDEO_GAMES.DBO.GAME AS GAME
JOIN VIDEO_GAMES.DBO.GAME_PUBLISHER AS GP ON GAME.ID = GP.GAME_ID
JOIN VIDEO_GAMES.DBO.PUBLISHER AS PUBLISHER ON GP.PUBLISHER_ID = PUBLISHER.ID
JOIN VIDEO_GAMES.DBO.GAME_PLATFORM AS GPL ON GP.ID = GPL.GAME_PUBLISHER_ID
JOIN VIDEO_GAMES.DBO.REGION_SALES AS RS ON GPL.ID = RS.GAME_PLATFORM_ID
JOIN VIDEO_GAMES.DBO.REGION AS REGION ON RS.REGION_ID = REGION.ID
WHERE REGION.REGION_NAME = 'NORTH AMERICA'
GROUP BY PUBLISHER.PUBLISHER_NAME
ORDER BY TOTAL_SALES DESC;

--9.Que editor genera mas juegos de accion
SELECT PUBLISHER.PUBLISHER_NAME, COUNT(*) AS TOTAL_ACTION_GAMES
FROM VIDEO_GAMES.DBO.GAME AS GAME
JOIN VIDEO_GAMES.DBO.GAME_PUBLISHER AS GP ON GAME.ID = GP.GAME_ID
JOIN VIDEO_GAMES.DBO.PUBLISHER AS PUBLISHER ON GP.PUBLISHER_ID = PUBLISHER.ID
JOIN VIDEO_GAMES.DBO.GENRE AS GENRE ON GAME.GENRE_ID = GENRE.ID
WHERE GENRE.GENRE_NAME = 'ACTION'
GROUP BY PUBLISHER.PUBLISHER_NAME
ORDER BY TOTAL_ACTION_GAMES DESC

--10.Cantidad de juegos de estrategia desarrollados por Microsoft
SELECT COUNT(*) AS TOTAL_STRATEGY_GAMES
FROM VIDEO_GAMES.DBO.GAME AS GAME
JOIN VIDEO_GAMES.DBO.GAME_PUBLISHER AS GP ON GAME.ID = GP.GAME_ID
JOIN VIDEO_GAMES.DBO.PUBLISHER AS PUBLISHER ON GP.PUBLISHER_ID = PUBLISHER.ID
JOIN VIDEO_GAMES.DBO.GENRE AS GENRE ON GAME.GENRE_ID = GENRE.ID
WHERE PUBLISHER.PUBLISHER_NAME = 'MICROSOFT' AND GENRE.GENRE_NAME = 'STRATEGY';
