---------------VIDEOGAME DB MYSQL--------------------

--1.Mostrar la lista de juegos con el genero
SELECT G.ID, G.GAME_NAME, GE.GENRE_NAME
FROM VIDEO_GAMES.GAME AS G
JOIN VIDEO_GAMES.GENRE AS GE ON G.GENRE_ID = GE.ID;

--2.Mostrar la lista de juegos que tiene cada Plataforma
ELECT P.PLATFORM_NAME, G.GAME_NAME
FROM VIDEO_GAMES.PLATFORM AS P
JOIN VIDEO_GAMES.GAME_PLATFORM AS GP ON P.ID = GP.PLATFORM_ID
JOIN VIDEO_GAMES.GAME AS G ON GP.GAME_ID = G.ID;

--3.Mostrar los juegos lanzados antes del año 2000
SELECT G.GAME_NAME
FROM VIDEO_GAMES.GAME_PLATFORM AS GP
JOIN VIDEO_GAMES.GAME AS G ON GP.ID = G.ID
WHERE GP.RELEASE_YEAR < 2000;

--4.Mostrar los juegos mas vendidos en Europa
SELECT G.GAME_NAME, RS.NUM_SALES
FROM VIDEO_GAMES.GAME AS G
JOIN VIDEO_GAMES.REGION_SALES AS RS ON G.ID = RS.GAME_PLATFORM_ID
JOIN VIDEO_GAMES.REGION AS R ON RS.REGION_ID = R.ID
WHERE R.REGION_NAME = 'EUROPA'
ORDER BY RS.NUM_SALES DESC;

--5.Mostrar los juegos con ventas menores al 0.5 de la plataforma Wii durante la decada del 2000
SELECT G.GAME_NAME, RS.NUM_SALES
FROM VIDEO_GAMES.GAME AS G
JOIN VIDEO_GAMES.GAME_PLATFORM AS GP ON G.ID = GP.ID
JOIN VIDEO_GAMES.REGION_SALES AS RS ON GP.ID = RS.GAME_PLATFORM_ID
JOIN VIDEO_GAMES.REGION AS R ON RS.REGION_ID = R.ID
WHERE GP.PLATFORM_ID = (SELECT ID FROM VIDEO_GAMES.PLATFORM WHERE PLATFORM_NAME = 'WII')
  AND RS.NUM_SALES < 0.5
  AND GP.RELEASE_YEAR >= 2000 AND GP.RELEASE_YEAR < 2010;

--6.Mostrar la lista de juegos de PlayStation
SELECT G.GAME_NAME
FROM VIDEO_GAMES.GAME AS G
JOIN VIDEO_GAMES.GAME_PLATFORM AS GP ON G.ID = GP.ID
JOIN VIDEO_GAMES.PLATFORM AS P ON GP.PLATFORM_ID = P.ID
WHERE P.PLATFORM_NAME = 'PLAYSTATION';

--7.Cuales son los 5 generos de juego que mas se venden en Europa
SELECT G.GENRE_NAME, SUM(RS.NUM_SALES) AS TOTAL_SALES
FROM VIDEO_GAMES.GAME AS GM
JOIN VIDEO_GAMES.GENRE AS G ON GM.GENRE_ID = G.ID
JOIN VIDEO_GAMES.REGION_SALES AS RS ON GM.ID = RS.GAME_PLATFORM_ID
JOIN VIDEO_GAMES.REGION AS R ON RS.REGION_ID = R.ID
WHERE R.REGION_NAME = 'EUROPE'
GROUP BY G.GENRE_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 5;

--8.Que editores tienen mejor presencia en el mercado de ventas de Norte America
SELECT P.PUBLISHER_NAME, SUM(RS.NUM_SALES) AS TOTAL_SALES
FROM VIDEO_GAMES.GAME_PUBLISHER AS GP
JOIN VIDEO_GAMES.PUBLISHER AS P ON GP.PUBLISHER_ID = P.ID
JOIN VIDEO_GAMES.GAME_PLATFORM AS GP2 ON GP.GAME_ID = GP2.ID
JOIN VIDEO_GAMES.REGION_SALES AS RS ON GP2.ID = RS.GAME_PLATFORM_ID
JOIN VIDEO_GAMES.REGION AS R ON RS.REGION_ID = R.ID
WHERE R.REGION_NAME = 'NORTEAMÉRICA'
GROUP BY P.PUBLISHER_NAME
ORDER BY TOTAL_SALES DESC;

--9.Que editor genera mas juegos de accion
SELECT P.PUBLISHER_NAME, COUNT(*) AS ACTION_GAMES_COUNT
FROM VIDEO_GAMES.GAME AS G
JOIN VIDEO_GAMES.GAME_PUBLISHER AS GP ON G.ID = GP.GAME_ID
JOIN VIDEO_GAMES.PUBLISHER AS P ON GP.PUBLISHER_ID = P.ID
JOIN VIDEO_GAMES.GENRE AS GE ON G.GENRE_ID = GE.ID
WHERE GE.GENRE_NAME = 'ACCIÓN'
GROUP BY P.PUBLISHER_NAME
ORDER BY ACTION_GAMES_COUNT DESC;

--10.Cantidad de juegos de estrategia desarrollados por Microsoft
SELECT COUNT(*) AS STRATEGY_GAMES_COUNT
FROM VIDEO_GAMES.GAME AS G
JOIN VIDEO_GAMES.GAME_PUBLISHER AS GP ON G.ID = GP.GAME_ID
JOIN VIDEO_GAMES.PUBLISHER AS P ON GP.PUBLISHER_ID = P.ID
JOIN VIDEO_GAMES.GENRE AS GE ON G.GENRE_ID = GE.ID
WHERE GE.GENRE_NAME = 'ESTRATEGIA' AND P.PUBLISHER_NAME = 'MICROSOFT';
