------------------------UNIVERSITY DB POSTGRES-----------------------------------------------

--1.REALIZAR UNA CONSULTA DONDE PUEDA OBTENER LOS PAISES DONDE ESTAN UBICADAS CADA UNIVERSIDAD.
SELECT U.UNIVERSITY_NAME, C.COUNTRY_NAME
FROM UNIVERSITIES.UNIVERSITY AS U
JOIN UNIVERSITIES.COUNTRY AS C ON U.COUNTRY_ID = C.ID;

--2. CONOCER CUANTAS UNIVERSIDADES HAY EN CADA PAIS.
SELECT C.COUNTRY_NAME, COUNT(U.ID) AS TOTAL_UNIVERSITIES
FROM UNIVERSITIES.COUNTRY AS C
LEFT JOIN UNIVERSITIES.UNIVERSITY AS U ON U.COUNTRY_ID = C.ID
GROUP BY C.COUNTRY_NAME;

--3. CONOCER CUANTOS PAISES NO TIENEN UNIVERSIDADES EN EL RANKING.
SELECT COUNT(*) AS TOTAL_PAISES_SIN_UNIVERSIDADES
FROM UNIVERSITIES.COUNTRY AS C
WHERE NOT EXISTS (
  SELECT 1
  FROM UNIVERSITIES.UNIVERSITY AS U
  WHERE U.COUNTRY_ID = C.ID
);

--4. MOSTRAR LOS CRITERIOS DE CADA TIPO DE RANKING.
SELECT RS.SYSTEM_NAME, RC.CRITERIA_NAME
FROM UNIVERSITIES.RANKING_SYSTEM AS RS
INNER JOIN UNIVERSITIES.RANKING_CRITERIA AS RC ON RS.ID = RC.RANKING_SYSTEM_ID

--5. CONOCER EL RANKING QUE TIENE MAS CRITERIOS
SELECT RS.SYSTEM_NAME, COUNT(RC.ID) AS NUM_CRITERIA
FROM UNIVERSITIES.RANKING_SYSTEM AS RS
INNER JOIN UNIVERSITIES.RANKING_CRITERIA AS RC ON RS.ID = RC.RANKING_SYSTEM_ID
GROUP BY RS.SYSTEM_NAME
ORDER BY NUM_CRITERIA DESC;

--6. CUAL ES EL TOP DE UNIVERSIDADES DE FORMA DESCENDENTE DEL ANO 2012 POR CADA CRITERIO
SELECT RC.CRITERIA_NAME, U.UNIVERSITY_NAME, URY.SCORE
FROM UNIVERSITIES.RANKING_CRITERIA AS RC
JOIN UNIVERSITIES.UNIVERSITY_RANKING_YEAR AS URY ON RC.ID = URY.RANKING_CRITERIA_ID
JOIN UNIVERSITIES.UNIVERSITY AS U ON U.ID = URY.UNIVERSITY_ID
WHERE URY.YEAR = 2012 AND RC.ID IN (
  SELECT DISTINCT RANKING_CRITERIA_ID
  FROM UNIVERSITIES.UNIVERSITY_RANKING_YEAR
  WHERE YEAR = 2012
)
ORDER BY RC.CRITERIA_NAME, URY.SCORE DESC;

--7. MOSTRAR LAS 5 UNIVERSIDAD CON MAS CANTIDADES DE SCORE 100 DEL RANKING TIPO 'CENTER FOR WORLD UNIVERSITY RANKINGS'
SELECT U.UNIVERSITY_NAME, COUNT(*) AS SCORE_COUNT
FROM UNIVERSITIES.UNIVERSITY_RANKING_YEAR AS URY
JOIN UNIVERSITIES.UNIVERSITY AS U ON U.ID = URY.UNIVERSITY_ID
JOIN UNIVERSITIES.RANKING_CRITERIA AS RC ON RC.ID = URY.RANKING_CRITERIA_ID
JOIN UNIVERSITIES.RANKING_SYSTEM AS RS ON RS.ID = RC.RANKING_SYSTEM_ID
WHERE RS.SYSTEM_NAME = 'CENTER FOR WORLD UNIVERSITY RANKINGS' AND URY.SCORE = 100
GROUP BY U.UNIVERSITY_NAME
ORDER BY SCORE_COUNT DESC
LIMIT 5;

--8. MOSTRAR QUE PAISES SE POSICIONARON CON UNIVERSIDADES CON UN SCORE MAYOR A 90
SELECT C.COUNTRY_NAME
FROM UNIVERSITIES.UNIVERSITY_RANKING_YEAR AS URY
JOIN UNIVERSITIES.UNIVERSITY AS U ON U.ID = URY.UNIVERSITY_ID
JOIN UNIVERSITIES.COUNTRY AS C ON C.ID = U.COUNTRY_ID
WHERE URY.SCORE > 90
GROUP BY C.COUNTRY_NAME;

--9. MOSTRAR LAS UNIVERSIDADES QUE UTILIZAN LOS CRITERIOS DEL TIPO RANKING 'SHANGAI RANKING'
SELECT U.UNIVERSITY_NAME
FROM UNIVERSITIES.UNIVERSITY AS U
JOIN UNIVERSITIES.RANKING_CRITERIA AS RC ON RC.ID = U.RANKING_CRITERIA_ID
JOIN UNIVERSITIES.RANKING_SYSTEM AS RS ON RS.ID = RC.RANKING_SYSTEM_ID
WHERE RS.SYSTEM_NAME = 'SHANGHAI RANKING';

--10. MOSTRAR EL TOP 10 DE LAS PEORES POSICIONES DEL TIPO RANKING 'TIMES HIGHER....'
SELECT U.UNIVERSITY_NAME, YR.YEAR, YR.SCORE
FROM UNIVERSITIES.UNIVERSITY AS U
JOIN UNIVERSITIES.UNIVERSITY_RANKING_YEAR AS YR ON YR.UNIVERSITY_ID = U.ID
JOIN UNIVERSITIES.RANKING_CRITERIA AS RC ON RC.ID = YR.RANKING_CRITERIA_ID
JOIN UNIVERSITIES.RANKING_SYSTEM AS RS ON RS.ID = RC.RANKING_SYSTEM_ID
WHERE RS.SYSTEM_NAME = 'TIMES HIGHER'
ORDER BY YR.SCORE ASC
LIMIT 10;








