-------------------SUPERHEROES BD POSTGRESS--------------------------

--1.Mostrar una lista de los superpoderes que tiene cada Super Heroe
SELECT S.SUPERHERO_NAME, SP.POWER_NAME
FROM SUPERHERO.SUPERHERO AS S
JOIN SUPERHERO.SUPERHERO_SUPERPOWER AS SS ON SS.SUPERHERO_ID = S.ID
JOIN SUPERHERO.SUPERPOWER AS SP ON SP.ID = SS.POWER_ID;

--2.Mostrar la cantidad de superpoderes con los que cuenta cada Super Heroe
SELECT S.SUPERHERO_NAME, COUNT(SS.POWER_ID) AS TOTAL_SUPERPOWERS
FROM SUPERHERO.SUPERHERO AS S
JOIN SUPERHERO.SUPERHERO_SUPERPOWER AS SS ON SS.SUPERHERO_ID = S.ID
GROUP BY S.SUPERHERO_NAME;

--3.Mostrar los diez superpoderes que es mas frecuente en cada Super Heroe
SELECT S.SUPERHERO_NAME, SP.POWER_NAME, COUNT(*) AS POWER_COUNT
FROM SUPERHERO.SUPERHERO AS S
JOIN SUPERHERO.SUPERHERO_SUPERPOWER AS SS ON SS.SUPERHERO_ID = S.ID
JOIN SUPERHERO.SUPERPOWER AS SP ON SP.ID = SS.POWER_ID
GROUP BY S.SUPERHERO_NAME, SP.POWER_NAME
ORDER BY S.SUPERHERO_NAME, POWER_COUNT DESC;

--4.Mostrar los diez superpoderes que es mas frecuente en cada Super Heroe
SELECT S.SUPERHERO_NAME, SP.POWER_NAME, COUNT(*) AS POWER_COUNT
FROM SUPERHERO.SUPERHERO AS S
JOIN SUPERHERO.SUPERHERO_SUPERPOWER AS SS ON SS.SUPERHERO_ID = S.ID
JOIN SUPERHERO.SUPERPOWER AS SP ON SP.ID = SS.POWER_ID
GROUP BY S.SUPERHERO_NAME, SP.POWER_NAME
ORDER BY S.SUPERHERO_NAME, POWER_COUNT DESC;

--5.Mostrar los Super Heroes que no cuentan con el Atributo de Intelligence
SELECT S.SUPERHERO_NAME
FROM SUPERHERO.SUPERHERO AS S
LEFT JOIN SUPERHERO.SUPERHERO_SUPERHERO_ATTRIBUTE AS SSA ON SSA.SUPERHERO_ID = S.ID
LEFT JOIN SUPERHERO.ATTRIBUTE AS A ON A.ID = SSA.ATTRIBUTE_ID
WHERE A.ATTRIBUTE_NAME <> 'INTELLIGENCE' OR A.ATTRIBUTE_NAME IS NULL;

--6.Mostrar los Super Heroes que cuentan con tres o 5 Atributos
SELECT S.SUPERHERO_NAME
FROM SUPERHERO.SUPERHERO AS S
JOIN (
  SELECT SUPERHERO_ID, COUNT(*) AS ATTRIBUTE_COUNT
  FROM SUPERHERO.SUPERHERO_SUPERHERO_ATTRIBUTE
  GROUP BY SUPERHERO_ID
  HAVING COUNT(*) = 3 OR COUNT(*) = 5
) AS COUNTS ON COUNTS.SUPERHERO_ID = S.ID;

--7.Mostrar la lista de las mujeres que son Super Heroes
SELECT SUPERHERO_NAME
FROM SUPERHERO.SUPERHERO
WHERE GENDER_ID = (
  SELECT ID
  FROM SUPERHERO.GENDER
  WHERE GENDER = 'FEMALE'
);

--8.Mostrar la lista de los colores de como se identifca un Super Heroe (color de ojos, traje y pelo)
SELECT DISTINCT COLOUR
FROM SUPERHERO.COLOUR
WHERE ID IN (
  SELECT SKIN_COLOUR_ID
  FROM SUPERHERO.SUPERHERO
);

--9.Mostrar la lista de Super Heroe indicando su origen (race) y cantidad de superpoderes
SELECT SH.SUPERHERO_NAME, R.RACE, COUNT(HP.POWER_ID) AS CANTIDAD_SUPERPODERES
FROM SUPERHERO.SUPERHERO SH
JOIN SUPERHERO.RACE R ON SH.RACE_ID = R.ID
LEFT JOIN SUPERHERO.HERO_POWER HP ON SH.ID = HP.HERO_ID
GROUP BY SH.SUPERHERO_NAME, R.RACE


--10.Mostrar la cantidad de superheroes que tienen un papel de Superheroe Bueno(alignment) agrupado por cada editor(publisher)
SELECT P.PUBLISHER_NAME, COUNT(SH.ID) AS CANTIDAD_SUPERHEROES
FROM SUPERHERO.SUPERHERO SH
JOIN SUPERHERO.PUBLISHER P ON SH.PUBLISHER_ID = P.ID
JOIN SUPERHERO.ALIGNMENT A ON SH.ALIGNMENT_ID = A.ID
WHERE A.ALIGNMENT = 'BUENO'
GROUP BY P.PUBLISHER_NAME